spring.application.name=ecommerce-project
server.port=5000

project.image.upload.path=images

spring.app.jwtExpirationTimeMs=3000000

spring.ecom.app.jwtCookieName=springBootEcom

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

#spring.data.redis.host=localhost
#spring.data.redis.host=host.docker.internal
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.cache-names=product-list
spring.data.redis.ssl.enabled=true

# Logs each request at DEBUG level
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=INFO

spring.jpa.show-sql=true