spring.application.name=ecommerce-project

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

project.image.upload.path=images

spring.app.jwtExpirationTimeMs=3000000

spring.ecom.app.jwtCookieName=springBootEcom

spring.profiles.active=local

# H2 database URL (in-memory)
#spring.datasource.url=jdbc:h2:mem:ecommerce
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.jpa.show-sql=true