spring.application.name=ecommerce-project

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

project.image.upload.path=images

spring.app.jwtExpirationTimeMs=3000000

spring.ecom.app.jwtCookieName=springBootEcom

spring.profiles.active=local

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.cache-names=product-list
#spring.cache.redis.time-to-live=300000

# H2 database URL (in-memory)
#spring.datasource.url=jdbc:h2:mem:ecommerce
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Logs each request at DEBUG level
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=INFO
#logging.level.org.springframework.security=INFO
#logging.level.com.ecommerce.project=DEBUG

spring.jpa.show-sql=true